[workspace]
authors = ["Sheldon Lobo <sheldon.m.lobo@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "learn"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026030105,<0.27"
